### PR TITLE
Add version stats for diaspora*

### PR DESCRIPTION
**Pull request by Flaburgan**
This is to help @SuperTux88 manage federation breaking changes :)
I had some weird result locally but I think this is because the data in my DB are not correct.
@jaywink I don't know if you still want to deploy things on dev.the-federation.info first. If so that could help me see if the code is buggy or not.

### CODE REVIEW

**Comment by jaywink** [comment]
Sorry I don't want to merge temporary code. Even though the code base is not super quality (the part I've written years ago), it still shouldn't be anything goes kind of thing. I'll happily merge the more generic implementation that checks for the latest version on github and makes stats on that.

However, I deployed this to dev side and it seems to work, so I see no reason not to deploy to the main site too. That is now done. Let me know when you don't need the stats any more and I will re-deploy master. Or if master gets some new commits then you need to rebase this :)

**Comment by SuperTux88** [comment]
> Sorry I don't want to merge temporary code.

Agree 👍 

I think a dropdown with versions and then "newer than version x" would be useful (to check how many pods/users already have a feature, because that's not always the latest version).

But the numbers are somehow "useless" without #22 anyway.

**Comment by jaywink** [comment]
This can probably be closed now that 0.7 is out.

**Comment by Flaburgan** [comment]
Yep, thank you to have put that online, very useful numbers :)

**Comment by SuperTux88** [comment]
Yes. 👍 It would still be cool to have a possibility to get stats how many servers or users use a version newer than x, but that would be cool for every version and every software, so it should be added in a generic way and not hardcoded.

**Pull request closed without merging**
